name: foodie
description: Suggest what to eat

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  http: ^0.13.4
  provider: ^6.0.3
  google_fonts: ^2.3.2
  shared_preferences: ^2.0.13
  cached_network_image: ^3.2.0

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/gif/

